# Generated by Django 3.2.8 on 2022-12-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='msg_subject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
